title: hawkl6rd
author: OpZ6
email: hawkl6rd@gmail.com
description: >-
  Just Photos

social:
  instagram: teo_luo
  github: OpZ6
  linkedin: tiancheng-luo-679b5a1b2

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-redirect-from

collections:
  images:
    output: true
